class Profile < ApplicationRecord


	FIRST_NAMES = [
		"Trant",
		"Bart",
		"Clarence",
		"Beeth",
		"Ben-Stacy",
		"John",
		"Tad",
		"Elsbeth",
		"Artemis",
		"September June",
		"Geryl",
		"Tam",
		"Monica",
		"Allen",
		"Mave",
		"Moose",
		"Natalie",
		"Paprika",
		"Twister",
		"Tiff",
		"Marty",
		"Tina",
		"Jennifurr",
		"Amelia",
		"Patricia",
		"Skyeana",
		"Dug",
		"Willa",
		"Tyra",
		"Bella",
		"Shelly",
		"Shannon",
		"Brynna",
		"Carla",
		"Petra",
		"Jane",
		"Charly",
		"Jeff",
		"Whoopsie",
		"Chappy",
		"Stephanie",
		"Mo",
		"Charles",
		"Jessica",
		"Babe",
		"Ignacio",
		"Fran",
		"Carmen",
		"Papa",
		"Tammy",
		"Molly",
		"Rebecca",
		"Lady",
		"Cheeburger",
		"Alyssa",
		"Byron",
		"Marbles",
		"Mitzi",
		"Tatiana",
		"Bubz",
		"Shonda",
		"Di",
		"Meredith",
		"Mary",
		"Lisa",
		"Kyle",
		"Pandora",
		"Champs",
		"Mason",
		"Meghain",
		"Janine",
		"Poot",
		"Sonia",
		"Manny",
		"Crishell",
		"Messica",
		"Bustin",
		"Jortney",
		"Ursula",
		"McKayleigh",
		"Everleigh",
		"Bo",
		"Whitney",
		"Floppiana",
		"Flapp",
		'Robert',
		"Joffrey",
		"Brock",
		"Frosty",
		"Daisy",
		"Bechamel",
		"Macy",
		"Duane",
		"Pappy",
		"Job",
		"DeBorah",
		"Kamala",
		"Spuds",
		"Princess",
		"Patty",
		"Jennifer",
		"Dan",
		"Eva",
		"Spencer",
		"Sam",
		"Daria",
		"Tobias",
		"Poppy",
		"Marvin",
		"Calvin",
		"Che",
		"Carrie",
		"Chungus",
		"Talia",
		"Julio",
		"Marcia",
		"Misty",
		"Babs",
		"Misha",
		"Mel",
		"Tony",
		"Gabriel",
		"Carl",
		"Polly",
		"Geraldine",
		"Fatima",
		"Janet",
		"Shailene",
		"Chaz",
		"Fats",
		"Barbie",
		"Tawny",
		"Bart",
		"Jesus",
		"Robby",
		"Belinda",
		"Paula",
		"Jerri",
		"Janiper",
		"Bingo",
		"Muriel",
		"Alicia",
		"Leonardo",
		"Randy",
		"Theodore",
		"Walter",
		"Tweety"
	]

	LAST_NAMES = [
		"Jandlin",
		"Sharty",
		"Tuttle",
		"Wylder",
		"Noelle",
		"Jacob-JingleHeimer (Née Schmidt)",
		"Fingley",
		"Früm",
		"Shpeath",
		"Raviolé",
		"Klump",
		"Girardi",
		"Peppercorn",
		"Bader Ginsberg",
		"Datthews",
		"Candiman",
		"Portmanteau",
		"Pringles",
		"McDouble",
		"Pappleby",
		"Diamondés",
		"Elefanto",
		"Smells",
		"Turndown",
		"Grossass",
		"Nintenda",
		"Marcaida",
		"Willie O'rwonte",
		"Denks",
		"O'No",
		"Breakfast",
		"Sandwich",
		"Smallz",
		"Hendrix",
		"Meltz",
		"Doe",
		"Bliss",
		"Probst",
		'Goldberg',
		"Buns",
		"Courtney",
		"Tuna",
		"Styles",
		"Fletcher",
		"Wheats",
		"Sprouts",
		"Douley",
		"Junior",
		"Moms",
		"McStar",
		"Melons",
		"Coffee",
		"Schmears",
		"Cheeburger",
		'Amitia',
		"Bae",
		"Houlihan",
		"Teapot",
		"Margarine",
		"Hardly",
		"Toyota",
		"Arrhea",
		"Marks",
		"Cosby",
		"Barlow",
		"Rinna",
		"Vanderpump",
		"McFlurry",
		"Jarr",
		"Lump",
		"Tipples",
		"DeLusseps",
		"Morgan",
		"Ketchum",
		"Barbenheim",
		"Horselegs",
		"Appleseed",
		"BobEsponja",
		"Grossman",
		"Broadway",
		"Myrtle - Wycoff",
		"Hongry",
		"Pucky",
		"McGoo",
		"Bones",
		"Moses",
		"Plath",
		"Chancletas-Gigantes",
		"Tipz",
		"Berenstaind",
		"Fieri",
		"Honey",
		"Reade",
		"Flapps",
		"Convertibles",
		"Doo",
		"Bouche",
		"Hahusband",
		"Pumpkins",
		"Loops",
		"Scales",
		"Dumberer",
		"Bynge-Wach",
		"Krood",
		"Boogie",
		"Domino",
		"Fleck",
		"Macklemore",
		"Maloney",
		"Bangs",
		"Sprite",
		"Diaz",
		"Bradshaw",
		"Payroni",
		"Nugs",
		"Sweats",
		"O'Tool",
		"Mayhem",
		"Malarkey",
		"Kronk",
		"Blimps",
		"Chowders",
		"Calhoun",
		"Otto-Madix",
		"Pelotón",
		"Cameldine",
		"Waffles",
		"Jamplin",
		"Birdles",
		"Coolbiens",
		"Sheetz",
		"Darby",
		"Down-Townes",
		"Nasty",
		"Sweets",
		"Z.",
		"Mush",
		"Korn",
		"Blank",
		"Boulay",
		"Pampe",
		"Dumps",
		"Theranos",
		"Tesla",
		"O'fish",
		"Blimps",
		"Wantafanta",
		"Bird"
	]

	OCCUPATIONS = [
		"Tax Evader",
		"Young Sheldon",
		"Orca Doula",
		"Bitcoin Collector",
		"Stamp Approver",
		"Olympic Jouster",
		"Independently Wealthy",
		"Tetris Ref",
		"Ghost Whisperer",
		"Test Stripper",
		"Shape Shifter",
		"Old Ass Bitch",
		"Sandwich Artist",
		"Bird Therapist",
		"Assistant Bus Driver",
		"Chronic Math Debater",
		"Wordplay Consultant",
		"Cruise Ship Improv Coach",
		"Bell Ringer",
		"Demon Heir",
		"Candle Waxer",
		"Stain Remover",
		"Third Wheel",
		"Dictionary Author",
		"Swamp Digger",
		"DIY Skydiving Instructor",
		"Sax Therapist",
		"Pen Pal",
		"Clockstopper",
		"Butt Doctor",
		"Gay Spy",
		"CEO, Bliss-finder.com",
		"Wiccan Baker",
		"Whistler",
		"Mallrat",
		"Zoologist to the Stars",
		"Lyrical Genius",
		"Climate Denier",
		"Clumsy Nun",
		"Female Vocalist Enthusiast/Still Somehow Hates Women",
		"Flo from the Progressive Commercials",
		"Water Sommelier",
		"Mystery Diner",
		"Murder Enthusiast",
		"Jester Flop in the Clown Square",
		"Wig Wrangler",
		"Paper Shredder",
		"Spy Kid",
		"Orphanage Villain",
		"Childless Wench",
		"Queen of Drag",
		"Filthy Rat",
		"Art historian with a concentration in friendship bracelets",
		"Burger Relations",
		"Camp Girlfriend",
		"Singer/Songreader",
		"Nightwalker",
		"War Criminal :(",
		"Dairy Advocate",
		"The Wet Wizard",
		"Lot Lizard",
		"Sewer Sherrif",
		"Rumors & Nastiness",
		"Occult Leader",
		"Depend Brand Ambassador",
		"Doll Sorcery",
		"Arsonist",
		"Trustfall Victim",
		"Getaway Car",
		"Mortician to the Stars",
		"Who's Line Understudy",
		"Former Countess",
		"Manager, Bubba Gump Times Square",
		"Time Traveler's Step Mom",
		"Coasting on looks",
		"Architectural Theory podcaster",
		"Medical Podcaster",
		"Hurdy Gurdy player",
		"Ugly Medieval Dog",
		"Hieronymus Bosch Demon Twink",
		"20th Generation Serf",
		"Orb Summoner",
		"Mocatriz (Modelo, Cantante, Actriz)",
		"Diggin up those holes",
		"Blue Man",
		"Watcher",
		"Competitive Nap Champion",
		"Feral Pig",
		"Removed the buttholes from Cats the Musical the movie.",
		"Marbles",
		"Daytime shift at the graveyard. Graveyard shift at Dennys.",
		"Three kids in a trenchcoat.",
		"Cowtipper",
		"Mercenary Assasin",
		"Can talk to animals. It’s really cool, but totally secret.",
		"Rain Dancer",
		"Nightmare Consultant",
		"Starbucks Unionizer",
		"Forest Ghoul",
		"Cat Medium",
		"Amish Influencer",
		"Cot Destroyer",
		"Spills the gatorade on the coach!",
		"Race Car Dryer",
		"Nine Inch Nail Tech",
		"Tables",
		"Professor, The Philosphy of Shrek",
		"Girlboss (unemployed)",
		"Sword Swallower",
		"Urban Lumberjack",
		"Tableside Guac-maker",
		"Comedy Concerts",
		"Slow Mime",
		"Bladesmith",
		"Pedicab Rental",
		"Author, Ventrilloquism for Dummies",
		"Ball Pit Sanitation",
		"Rat Czar",
		"Seaworld Whistle Blower",
		"Door to door doorknob salesman",
		"My single 'My single is dropping' is dropping 10/24",
		"Chowder Chomper",
		"Bill Gates Impersonator",
		"None of your business",
		"Founding member of P.O.D.",
		"Pet Masseuse",
		"Midnight Oil Painter",
		"Saucier to the stars",
		"Party Rocker (In the house, tonight)",
		"Kidz Bop Musical Director",
		"Human Scarecrow",
		"Doll Hairdresser",
		"Intern, Califia Oat Milk",
		"Walking children in nature",
		"Roller Coaster Imagineer",
		"Bar Mitzvah DJ",
		"Carny",
		"Competitive Butter Eater",
		"A boozer, a user, and a LOSER. (I stole the TV!)",
		"Still get an allowance",
		"Mouth Model",
		"Deep Sea Dumpster Diver",
		"Run an indendent blood bank",
		"Sensei In Training",
		"Tasmanian Devil's Advocate",
		"President, AVATAR fan club",
		"Gentle Dominatrix",
		"Vibes"
	]

	# If you want to access that array from the inside class, just do FIRST_NAME, and from the outside class use Profile::FIRST_NAMES

	def random_first_name
		FIRST_NAMES.sample
	end

	def random_last_name
		LAST_NAMES.sample
	end

	def random_full_name
		"#{random_first_name}" + "#{random_last_name}"
	end

	def random_occupation
		OCCUPATIONS.sample
	end

end
