class Profile < ApplicationRecord

	mount_uploader :profile_image, ProfileImageUploader

	def full_name
		[first_name, last_name].join(" ")
	end


	FIRST_NAMES = [
		"Trant",
		"Bart",
		"Clarence",
		"Beeth",
		"Ben-Stacy",
		"John",
		"Tad",
		"Elsbeth",
		"Artemis",
		"September June",
		"Geryl",
		"Tam",
		"Monica",
		"Allen",
		"Mave",
		"Moose",
		"Natalie",
		"Paprika",
		"Twister",
		"Tiff",
		"Marty",
		"Tina",
		"Jennifurr",
		"Amelia",
		"Patricia",
		"Skyeana",
		"Dug",
		"Willa",
		"Tyra",
		"Bella",
		"Shelly",
		"Shannon",
		"Brynna",
		"Carla",
		"Petra",
		"Jane",
		"Charly",
		"Jeff",
		"Whoopsie",
		"Chappy",
		"Stephanie",
		"Mo",
		"Charles",
		"Jessica",
		"Babe",
		"Ignacio",
		"Fran",
		"Carmen",
		"Papa",
		"Tammy",
		"Molly",
		"Rebecca",
		"Lady",
		"Cheeburger",
		"Alyssa",
		"Byron",
		"Marbles",
		"Mitzi",
		"Tatiana",
		"Bubz",
		"Shonda",
		"Di",
		"Meredith",
		"Mary",
		"Lisa",
		"Kyle",
		"Pandora",
		"Champs",
		"Mason",
		"Meghain",
		"Janine",
		"Poot",
		"Sonia",
		"Manny",
		"Crishell",
		"Messica",
		"Bustin",
		"Jortney",
		"Ursula",
		"McKayleigh",
		"Everleigh",
		"Bo",
		"Whitney",
		"Floppiana",
		"Flapp",
		'Robert',
		"Joffrey",
		"Brock",
		"Frosty",
		"Daisy",
		"Bechamel",
		"Macy",
		"Duane",
		"Pappy",
		"Job",
		"DeBorah",
		"Kamala",
		"Spuds",
		"Princess",
		"Patty",
		"Jennifer",
		"Dan",
		"Eva",
		"Spencer",
		"Sam",
		"Daria",
		"Tobias",
		"Poppy",
		"Marvin",
		"Calvin",
		"Che",
		"Carrie",
		"Chungus",
		"Talia",
		"Julio",
		"Marcia",
		"Misty",
		"Babs",
		"Misha",
		"Mel",
		"Tony",
		"Gabriel",
		"Carl",
		"Polly",
		"Geraldine",
		"Fatima",
		"Janet",
		"Shailene",
		"Chaz",
		"Fats",
		"Barbie",
		"Tawny",
		"Bart",
		"Jesus",
		"Robby",
		"Belinda",
		"Paula",
		"Jerri",
		"Janiper",
		"Bingo",
		"Muriel",
		"Alicia",
		"Leonardo",
		"Randy",
		"Theodore",
		"Walter",
		"Tweety"
	]

	LAST_NAMES = [
		"Jandlin",
		"Sharty",
		"Tuttle",
		"Wylder",
		"Noelle",
		"Jacob-JingleHeimer (Née Schmidt)",
		"Fingley",
		"Früm",
		"Shpeath",
		"Raviolé",
		"Klump",
		"Girardi",
		"Peppercorn",
		"Bader Ginsberg",
		"Datthews",
		"Candiman",
		"Portmanteau",
		"Pringles",
		"McDouble",
		"Pappleby",
		"Diamondés",
		"Elefanto",
		"Smells",
		"Turndown",
		"Grossass",
		"Nintenda",
		"Marcaida",
		"Willie O'rwonte",
		"Denks",
		"O'No",
		"Breakfast",
		"Sandwich",
		"Smallz",
		"Hendrix",
		"Meltz",
		"Doe",
		"Bliss",
		"Probst",
		'Goldberg',
		"Buns",
		"Courtney",
		"Tuna",
		"Styles",
		"Fletcher",
		"Wheats",
		"Sprouts",
		"Douley",
		"Junior",
		"Moms",
		"McStar",
		"Melons",
		"Coffee",
		"Schmears",
		"Cheeburger",
		'Amitia',
		"Bae",
		"Houlihan",
		"Teapot",
		"Margarine",
		"Hardly",
		"Toyota",
		"Arrhea",
		"Marks",
		"Cosby",
		"Barlow",
		"Rinna",
		"Vanderpump",
		"McFlurry",
		"Jarr",
		"Lump",
		"Tipples",
		"DeLusseps",
		"Morgan",
		"Ketchum",
		"Barbenheim",
		"Horselegs",
		"Appleseed",
		"BobEsponja",
		"Grossman",
		"Broadway",
		"Myrtle - Wycoff",
		"Hongry",
		"Pucky",
		"McGoo",
		"Bones",
		"Moses",
		"Plath",
		"Chancletas-Gigantes",
		"Tipz",
		"Berenstaind",
		"Fieri",
		"Honey",
		"Reade",
		"Flapps",
		"Convertibles",
		"Doo",
		"Bouche",
		"Hahusband",
		"Pumpkins",
		"Loops",
		"Scales",
		"Dumberer",
		"Bynge-Wach",
		"Krood",
		"Boogie",
		"Domino",
		"Fleck",
		"Macklemore",
		"Maloney",
		"Bangs",
		"Sprite",
		"Diaz",
		"Bradshaw",
		"Payroni",
		"Nugs",
		"Sweats",
		"O'Tool",
		"Mayhem",
		"Malarkey",
		"Kronk",
		"Blimps",
		"Chowders",
		"Calhoun",
		"Otto-Madix",
		"Pelotón",
		"Cameldine",
		"Waffles",
		"Jamplin",
		"Birdles",
		"Coolbiens",
		"Sheetz",
		"Darby",
		"Down-Townes",
		"Nasty",
		"Sweets",
		"Z.",
		"Mush",
		"Korn",
		"Blank",
		"Boulay",
		"Pampe",
		"Dumps",
		"Theranos",
		"Tesla",
		"O'fish",
		"Blimps",
		"Wantafanta",
		"Bird"
	]

	OCCUPATIONS = [
		"Tax Evader",
		"Young Sheldon",
		"Orca Doula",
		"Teach Children the Importance of Bitcoin",
		"Competitive Basket Weaver",
		"Olympic Jouster",
		"Independently Wealthy",
		"Make Kombucha in Old Shoes",
		"Ghost Whisperer",
		"Jello Wrestler",
		"Shape Shifter",
		"Old Ass Bitch",
		"Abstract Sandwich Artist",
		"Bird Therapist",
		"Assistant Bus Driver",
		"Chronic Math Debater",
		"Still posting my Wordle results daily",
		"First time caller, long time wiretapper",
		"Bell Ringer",
		"Demon Heir",
		"Industry Disruptor, CEO of Stanky Candles",
		"Stain Remover",
		"Third Wheel",
		"Elder Wizard from the Forgotten Realm",
		"Swamp Digger",
		"DIY Skydiving Instructor",
		"Sax Therapist",
		"EpiPen Pal",
		"Clockstopper",
		"Butt Doctor",
		"Gay Spy",
		"CEO, Bliss-finder.com",
		"Wiccan Baker",
		"Tuvan Throat Singer",
		"Mallrat",
		"Zoologist to the Stars",
		"Lyrical Genius",
		"Fighting global warming by putting a bunch of ice cubes in the ocean",
		"Clumsy Nun",
		"Female Vocalist Enthusiast/Still Somehow Hates Women",
		"Flo from the Progressive Commercials",
		"Water Sommelier",
		"Mystery Diner",
		"Murder Enthusiast",
		"Jester Flop in the Clown Square",
		"Wig Wrangler",
		"Shred Confidential Military Documents. Don’t ask… ;)",
		"Spy Kid",
		"Corrupt Orphanage Director",
		"Childless Wench",
		"Conservative Drag Queen",
		"Filthy Rat",
		"Art historian with a concentration in friendship bracelets",
		"Plant based gardener",
		"Camp Girlfriend",
		"Singer/Songreader",
		"Nightwalker",
		"War Criminal :(",
		"Dairy Advocate",
		"The Wet Wizard",
		"Lot Lizard",
		"Sewer Sherrif",
		"Rumors & Nastiness",
		"Writer, Jonas Brothers Fan Fic",
		"Depend Brand Ambassador",
		"Doll Sorcery",
		"Arsonist",
		"Trustfall Victim",
		"Getaway Car",
		"Mortician to the Stars",
		"Creator of “Whose Line ISN’T It Anyway” an improv show where everyone talks over each other",
		"Former Countess",
		"Manager, Bubba Gump Times Square",
		"Time traveler sent back to stop you",
		"Coasting on looks",
		"Conspiracy Theory Podcaster",
		"Medical Podcaster",
		"Hurdy Gurdy player",
		"Ugly Medieval Dog",
		"Hieronymus Bosch Demon Twink",
		"Flesh vessel for a 17th century peasant child",
		"Orb Summoner",
		"Triple Threat (Sing, Dance, Contemplate Death)",
		"Diggin up those holes",
		"Blue Man",
		"Always Watching...",
		"Competitive Nap Champion",
		"Feral Pig",
		"Removed the buttholes from Cats the Musical the movie.",
		"Marbles",
		"Daytime shift at the graveyard. Graveyard shift at Dennys.",
		"Three kids in a trenchcoat.",
		"Cowtipper",
		"Mercenary Assasin",
		"Can talk to animals. It’s really cool, but totally secret.",
		"Rain Dancer",
		"Nightmare Consultant",
		"Starbucks Unionizer",
		"Forest Ghoul",
		"Cat Medium",
		"Amish Influencer",
		"Guinness Record, Worst case of athlete’s foot",
		"Spills the gatorade on the coach!",
		"Race Car Dryer",
		"Nine Inch Nail Tech",
		"Tables",
		"Professor, The Sociopolitical Impact of Shrek 2 in the Middle East",
		"Girlboss (unemployed)",
		"Sword Swallower",
		"Urban Lumberjack",
		"Tableside Guac-maker",
		"Prop Comedian, opening for Che Diaz's next comedy concert",
		"Loud Mime",
		"Bladesmith",
		"Pedicab Rental",
		"Author, Ventrilloquism for Dummies",
		"Ball Pit Sanitation",
		"Rat Czar",
		"Seaworld Whistle Blower",
		"Door to door doorknob salesman",
		"My single 'My single is dropping' is dropping 10/24",
		"Chowder Chomper",
		"Bill Gates Impersonator",
		"None of your business",
		"Founding member of P.O.D.",
		"Pet Masseuse",
		"Midnight Oil Painter",
		"Saucier to the stars",
		"Party Rocker (In the house, tonight)",
		"Kidz Bop Musical Director",
		"Human Scarecrow",
		"Real Housewife of Albuquerque",
		"Intern, Califia Oat Milk",
		"Walking children in nature",
		"Roller Coaster Imagineer",
		"Bar Mitzvah DJ",
		"Carny",
		"Competitive Butter Eater",
		"A boozer, a user, and a LOSER. (I stole the TV!)",
		"Still get an allowance",
		"Mouth Model",
		"Deep Sea Dumpster Diver",
		"The New Hadid",
		"Sensei In Training",
		"Tasmanian Devil's Advocate",
		"President, AVATAR fan club the Na'ViGators",
		"Gentle Dominatrix",
		"Vibes"
	]

	# If you want to access that array from the inside class, just do FIRST_NAME, and from the outside class use Profile::FIRST_NAMES

	def random_first_name
		FIRST_NAMES.sample
	end

	def random_last_name
		LAST_NAMES.sample
	end

	def random_full_name
		[random_first_name, random_last_name].join(" ")
	end

	def random_occupation
		OCCUPATIONS.sample
	end

	def random_age
		(18..100).to_a.sample
	end

end
